services:
  postgres:
    container_name: postgres-pern
    image: postgres:13-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - PGDATABASE=pern
      - POSTGRES_DB=pern
      - PGUSER=admin
      - POSTGRES_USER=admin
      - PGPASSWORD=password
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  pgweb:
    container_name: pgweb-pern
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres
    environment:
      - DATABASE_URL=postgres://admin:password@postgres/pern?sslmode=disable

  node-js:
    image: node:16-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_DB=pern
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    links:
      - postgres
    working_dir: /app
    volumes:
      - ./:/app

volumes:
  db:
